app/assets/stylesheets/static.scss, app/views/static/index.html.erb
Fix the overflow errors on mobile
=> Responsive Slide Captions

app/controllers/static_controller.rb
=> Fix: upcoming events showing events from one day earlier

app/assets/javascripts/menu.coffee, app/assets/stylesheets/application.css, app/assets/stylesheets/course_review.scss, app/controllers/course_review_controller.rb, app/controllers/courses_controller.rb, app/helpers/course_review_helper.rb, app/models/course.rb, app/models/course_review.rb, app/models/instructor.rb, app/views/components/_application_header.html.erb, app/views/components/_star_reviews.html.erb, app/views/course_review/create.html.erb, app/views/course_review/show.html.erb, app/views/courses/index.html.erb, app/views/courses/partials/_course_list.html.erb, app/views/courses/partials/_course_schedule.html.erb, app/views/courses/show.html.erb, config/routes.rb, db/migrate/20181107040015_create_course_reviews.rb, db/schema.rb, lib/tasks/review_import.rake, test/controllers/course_review_controller_test.rb, test/fixtures/course_reviews.yml, test/models/course_review_test.rb
BIG push
Probably some things that need to be changed / refactored, but all-in-all, I believe this is a pretty solid feature for the time crunch we're facing
=> Create course reviews and import

app/views/menu/_dining_hall_menu.html.erb, lib/tasks/menu_import.rake
Updated rake task to clear Claremont McKenna and Pitzer menus before importing in order to avoid duplicate entries.
=> Fix menu hours 

app/views/static/aspc_pec.html.erb
Added content to Pomona Events Committee page.
=> Update PEC page

app/views/menu/index.html.erb, lib/tasks/menu_import.rake
Combine Frary Sunday breakfast/lunch listing into brunch
=> Hide brunch on weekends, breakfast/lunch on weekdays

app/assets/javascripts/courses.js, app/assets/stylesheets/courses.scss, app/controllers/courses_controller.rb, app/views/courses/index.html.erb, app/views/courses/partials/_course_schedule.html.erb, app/views/courses/partials/_course_search_form.html.erb
Updated course scheduler search user interface. Added time filter to course scheduler search.
=> Course scheduler improvements

app/assets/stylesheets/courses.scss, app/views/courses/partials/_course_schedule.html.erb
=> Hotfix for course list on course scheduler 

app/assets/stylesheets/static.scss, app/views/static/index.html.erb
Added arrows to the carousel. Added a button that opens announcement URL. Fixed carousel flickering by adding the following options to Slick plugin: 
` useTransform: false, easing: 'swing'`
=> Carousel UI

app/controllers/courses_controller.rb, app/views/courses/partials/_course_search_form.html.erb, config/environments/development.rb
Fixes #88 and fixes time selection (allows one of start time and end time to be specified)
=> Revert course search form to checkboxes; fix time selection

app/controllers/static_controller.rb, app/views/static/index.html.erb
Updated static controller and `index.html.erb` to fetch the latest Student Life articles from their RSS feed.
=> Latest TSL articles on index page

Gemfile, app/assets/javascripts/application.js, app/views/layouts/application.html.erb
=> Remove turbolinks

app/admin/announcements.rb, app/admin/courses.rb, app/admin/dashboard.rb, app/admin/departments.rb, app/admin/events.rb, app/admin/instructors.rb, app/admin/people.rb, app/admin/static.rb, app/admin/users.rb, app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/helpers/events_helper.rb, app/helpers/static_helper.rb, app/models/active_admin_authorization_adapter.rb, app/models/admin_authorization_adapter.rb, app/models/contributor_authorization_adapter.rb, app/models/static.rb, app/models/user.rb, app/views/admin/statics/_static_page_content_editor.html.erb, app/views/admin/statics/_static_page_edit_form.html.erb, app/views/components/_application_header.html.erb, app/views/static/show.html.erb, config/initializers/active_admin.rb, config/routes.rb, db/migrate/20190328194029_add_columns_to_user.rb, db/schema.rb
#120 
Creates the contributor role -- like an admin, but only with the ability to create pages / events / announcements -- on the admin portal.
=> #120 - Add admin contributor role

app/controllers/courses_controller.rb
=> Update term start and end for fall 2019

app/controllers/courses_controller.rb, app/views/courses/partials/_course_search_form.html.erb, db/schema.rb
Commented out time filter field from the form. Controller should handle the case when there is no input in time filter.
=> Remove time filter from scheduler

app/assets/stylesheets/application.css, app/views/components/_application_footer.html.erb, app/views/static/index.html.erb
Corrected links for events, heading fonts and footer responsiveness.
=> Hotfixes for new UI

app/assets/stylesheets/application.css, app/assets/stylesheets/courses.scss, app/views/courses/index.html.erb, app/views/courses/partials/_course_list.html.erb, app/views/courses/partials/_course_search_form.html.erb, package.json, yarn.lock
Updated course scheduler user interface to match new visual language used in website redesign.
=> Course scheduler UI improvements

app/assets/stylesheets/application.css, app/assets/stylesheets/overrides.scss, app/assets/stylesheets/static.scss, app/views/components/_application_footer.html.erb, app/views/components/_application_header.html.erb, app/views/static/aspc_senators.html.erb, app/views/static/index.html.erb, app/views/static/resources_coop_fountain.html.erb
- Fixed Event Calendar link on home page
- Fixed overflow issue with modal dialogs on Senators page
- Restyled a few default Bulma components to better match current visual language
- Updated footer icons and links
- Applied rounded borders to menus in Coop Fountain page
=> Various small changes

app/assets/stylesheets/overrides.scss, app/views/events/_event_form.html.erb, app/views/events/show.html.erb
- Consistent form fields in `_event_form.html.erb`
- Updated buttons on events calendar to match our current visual language
- Updated colors of export buttons in `events/show.html.erb` to match current color scheme
=> More small changes

app/assets/stylesheets/housing_reviews.scss, app/assets/stylesheets/static.scss, app/views/housing_rooms/show_buildings.html.erb
Put back in the code that makes senator and housing images uniform in size. I accidentally removed this in #133.
=> Hotfix: senator and housing uniform image sizes

app/views/housing_rooms/show_building_rooms.html.erb
Cast string of room number to int
=> Fix housing room number sorting

app/assets/javascripts/courses.js, app/assets/stylesheets/application.css, app/assets/stylesheets/courses.scss, app/controllers/courses_controller.rb, app/controllers/instructors_controller.rb, app/views/components/_application_header.html.erb, app/views/components/_star_review_input.erb, app/views/courses/add_review_course_section.html.erb, app/views/courses/partials/_reviews_course_list.html.erb, app/views/courses/partials/_reviews_search_form.html.erb, app/views/courses/reviews.html.erb, app/views/courses/search_course_sections.js.erb, app/views/instructors/add_instructor_review.html.erb, app/views/instructors/index.html.erb, app/views/instructors/partials/_instructors_list.html.erb, app/views/instructors/partials/_instructors_search_form.html.erb, app/views/instructors/search.js.erb, config/routes.rb
Created pages to search course and instructors and to submit reviews for both courses and instructors. I could not get instructor search to list courses each instructor taught last semester.
=> Course and instructor reviews improvements

app/admin/users.rb, app/controllers/application_controller.rb
Admins now have the capability to impersonate / log in as another user, to better troubleshoot and reproduce issues individual users are facing.
To do this: 
Login to the admin panel > go to users > select the user you wish to impersonate > click "impersonate"
=> User impersonation

app/models/course.rb, app/models/instructor.rb, lib/tasks/course_import.rake, lib/tasks/review_import.rake
Skip validations on legacy course review import
=> Update course review import

app/controllers/course_reviews_controller.rb
Move keyword search to the db level to avoid unnecessary filtering in controller
=> More efficient course review searching

lib/tasks/menu_import.rake
Mudd fixed their menu service! We can use their API directly, instead of looking at historical menus.
=> Fixing mudd rake task

app/views/components/_application_header.html.erb
Creates a link to the JBoard home page 
cc @srichards11
=> Add jboard page

app/views/courses/partials/_course_modal.html.erb, app/views/courses/partials/_course_schedule.html.erb
fixed bug where you cannot close modal after you remove/add course to course planner
=> fix course modal

Dockerfile, app/views/static/index.html.erb
added correct links for voting and funding
=> updated links voting, funding

app/views/components/_application_header.html.erb
reroute the current Login button directly to the CAS page
=> added CAS sign in to homepage

app/views/course_reviews/partials/_reviews_course_search_form.html.erb, app/views/courses/partials/_course_search_form.html.erb
Adding animated spinner and "Loading" to course searches to indicate that the results are being fetched. 
**On Course Review Search:**
Before _Search_ is clicked:
While results are being fetched:
**On Course Planner Search:**
Before _Search_ is clicked:
While results are being fetched:
=> add loading spinner to course searches

app/controllers/course_reviews_controller.rb
Previously, you would get no search results if you only searched using course number. 
This fixes that.
=> Fix course review search

app/controllers/static_controller.rb, app/views/static/index.html.erb
=> Revert "Reactivate TSL section"

app/controllers/application_controller.rb
Changed from login_path to login_cas
=> Change default auth path to cas

app/controllers/application_controller.rb
login_cas needs symbol syntax notation
=> Added colon before login_cas

vendor/assets/javascripts/fullcalendar-3.9.0/fullcalendar.js
| Format | Before    | After |
| ----------- | ----------- | ----------- |
|  desktop   |   <img width="774" alt="image" src="https://user-images.githubusercontent.com/78676977/197370039-81ae437f-9905-401a-b73b-69d8e6301d28.png">    | <img width="803" alt="image (1)" src="https://user-images.githubusercontent.com/78676977/197370057-da3e76fb-1d19-467f-aa95-5545db7d867f.png">  |
| mobile   |  <img width="210" alt="image (2)" src="https://user-images.githubusercontent.com/78676977/197370089-a0be7be3-5a7e-4fd7-aa6d-90a0544d7829.png">  | <img width="212" alt="image (3)" src="https://user-images.githubusercontent.com/78676977/197370090-801a6377-4ff0-455f-86db-e562d12413e3.png"> |
=> fixed calendar height on desktop & mobile

app/views/components/_application_header.html.erb
=> Added wellness resource guide

app/assets/stylesheets/application.css, app/views/components/_application_footer.html.erb
| Before      | After |
| ----------- | ----------- |
|<img width="987" alt="image" src="https://user-images.githubusercontent.com/78676977/205527777-8bb945e7-ea05-4bef-8019-86c208d98883.png"> | <img width="981" alt="image" src="https://user-images.githubusercontent.com/78676977/205527847-a6bea4ec-6e43-4106-a436-663c0ca73e85.png">     |
=> fixed social media icon

app/views/static/index.html.erb
=> Update to Spring 23

app/assets/stylesheets/static.scss, app/views/static/senior_class.html.erb, config/routes.rb
Added graduation countdown and re-used old content from the original senior class page.
=> Created /seniorclass page, added graduation countdown

app/views/static/index.html.erb
=> added covid isolation faq

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb
Test: Store last page in sessions just before authentication, and redirect to same page after login
=> Add variable for last_index_page

app/controllers/sessions_controller.rb
Add redirect functionality to :new method
=> Add redirect to last page for :new

app/controllers/sessions_controller.rb
=> Revert "Fix/vote redir"

app/controllers/sessions_controller.rb
After cas credentials login, redirect to /vote if that is where we came from
=> If came from vote, redit to vote after login

app/controllers/sessions_controller.rb
=> Revert "If came from vote, redit to vote after login"

app/views/sessions/new.html.erb
=> Deleted 5C Login Option for vote-app

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb
=> Revert "Add variable for last_index_page"

app/assets/stylesheets/overrides.scss, app/views/housing_rooms/show_buildings.html.erb, yarn.lock
1. Added housing page's padding between North and South section
2. Made housing boxes equal in length 
Before: Boxes are not equal in height, and no padding between the North and South sections:
After:
=> Add housing page's padding between North and South section

app/controllers/courses_controller.rb
=> Added FA2023

app/views/components/_application_header.html.erb
Added resource guide to navbar. Removed COVID Community Agreement.
=> added resource guide

app/controllers/courses_controller.rb
=> Added SP24

app/views/housing_reviews/_form.html.erb
* Removed PDF & GIF from image upload types.
=> Remove pdf and gif

app/controllers/courses_controller.rb
Added FA2024 Courses
Should update in the future to automate this process.
=> Added FA2024 courses

Dockerfile, app/controllers/courses_controller.rb
=> new courses for sp25

Dockerfile, config/deploy.rb, config/deploy/production.rb, config/environments/development.rb, config/environments/production.rb, docker-compose.yml, docker/entrypoint.sh
This reverts commit b4903ad495b68c8639355da1ef3743d74fd55e56.
=> Revert "Fixing logging issues"
